### PR TITLE
fix: correctly ignore .gitignore when a .npmignore is present outside of the workspace tree

### LINKED ISSUE #106: [BUG] workspace root `.gitignore` supersed every `.npmignore` and `.gitignore`
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Given that I have a gitignore at the root level of my workspaces, it will supersed the `.gitignore` and the `.npmignore` at the workspace level.

This means that when I run `npm publish` at the level of a single package, it ends up using the root `.gitignore` to filter out files.

### Expected Behavior

I would expect the 'ignore file resolution' order to be a such:
1. 'ws-local' `.npmignore`
2. 'ws-local' `.gitignore`
3. 'ws-root' `.npmignore`
4. 'ws-root' `.gitignore`

### Steps To Reproduce

1. In this environment:
```
.
├── .gitignore // file content: dist
├── .npmignore // empty file
├── package.json
└── packages
    └── a
        ├── dist
        │   └── test.js
        ├── .gitignore // empty file or anything but dist
        ├── .npmignore // empty file
        └── package.json
```
2. With `npm 8.11.0`
3. Run `npm publish --dry-run` while cwd is `packages/a`
4. See that `dist/test.js` is not included.

### Environment

- npm: 8.11.0
- Node: 16.15.0
- OS: W10/Debian(WSL)
- platform: N.A.

### PR DESCRIPTION
**Pull request by nlf**
previously we were concatting the .npmignore to the .gitignore and using both, which is incorrect. this ensures if a .npmignore exists we only use those rules.

closes #106

### CODE REVIEW

File: lib/index.js [hunk 1]
```diff
@@ -34,10 +34,13 @@ const glob = require('glob')
...
 const readOutOfTreeIgnoreFiles = (root, rel, result = '') => {
-  for (const file of ['.gitignore', '.npmignore']) {
+  for (const file of ['.npmignore', '.gitignore']) {
     try {
       const ignoreContent = fs.readFileSync(path.join(root, file), { encoding: 'utf8' })
       result += ignoreContent + '\n'
+      // break the loop immediately after concatting, this allows us to prioritize the
+      // .npmignore and discard the .gitignore if one exists
+      break
     } catch (err) {
```
Comment (louis-bompart) [inline lib/index.js:44]: I reckon that, if I have a `npmignore` and `gitignore` at `workspaces/foo` but only a `gitignore` in workspaces (or any folder in between) or at the root level, I will endup with a result:
```
content of npmignore from foo
content of gitignore from workspace
content of gitignore from root
```

It seems odd to me to mix the npmignore and gitignore (ofc, if that the expected behavior, all good 👍 )

Comment (nlf) [reply lib/index.js:44]: that's the expected behavior, if a directory does not contain a `.npmignore` but does have a `.gitignore` then we respect the `.gitignore`

Comment (louis-bompart) [reply lib/index.js:44]: 👍 if that's the expected behaviour, then all's well.
I think you still need to reverse the result concatenation because you're crawling up the tree, but I might be mistaken.
```suggestion
  for (const file of ['.npmignore', '.gitignore']) {
    try {
      const ignoreContent = fs.readFileSync(path.join(root, file), { encoding: 'utf8' })
      result = ignoreContent + '\n' + result
      // break the loop immediately after concatting, this allows us to prioritize the
      // .npmignore and discard the .gitignore if one exists
      break
    } catch (err) {
```

Comment (nlf) [reply lib/index.js:44]: we're crawling from the root deeper toward the workspace, you can see when we call `readOutOfTreeIgnoreFiles` here: https://github.com/npm/npm-packlist/blob/main/lib/index.js#L166 we're passing it `opt.prefix` which is the `/root`, and `relpath` to carry with your examples in #108 would be the string `packages`

the loop runs with `root`, then appends the next segment of the relpath (`packages`) and runs again, concatting this result to the end, this gives us the expected order of rules

**Review by louis-bompart — APPROVED** [review]
LGTM, thanks for this quickfix @nlf

**Review by wraithgar — APPROVED** [review]
That's quite a story being told in the test.
